---
name: Container Image CI

on:
  push:
    branches:
      - "main"
      - "release-.*"
    paths:
      - 'deployments/containerfiles/Containerfile-api'
      - 'deployments/containerfiles/Containerfile-agent'
      - 'deployments/containerfiles/Containerfile-scanner'
  pull_request:
    branches:
      - "main"
      - "release-.*"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Quay.io
        run: |
          echo "${{ secrets.QUAY_PASSWORD }}" | docker login quay.io -u "${{ secrets.QUAY_USERNAME }}" --password-stdin

      - name: Build and push image
        run: |
          IMAGE_NAME="quay.io/YOUR_ORG/YOUR_IMAGE:latest"  # Reemplaza con tu organización e imagen en Quay.io
          docker build -t $IMAGE_NAME -f deployments/containerfiles/Containerfile-api .
          docker push $IMAGE_NAME

      - name: Logout from Quay.io
        run: docker logout quay.io

