version: "2"
run:
  relative-path-mode: gomod
  modules-download-mode: readonly
  tests: false
linters:
  default: none
  enable:
    - containedctx
    - copyloopvar
    - cyclop
    - errcheck
    - exhaustive
    - gochecksumtype
    - goconst
    - gocritic
    - govet
    - inamedparam
    - ineffassign
    - misspell
    - mnd
    - noctx
    - revive
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - internal/inventory/tag_test.go
      - .*.pb.go
      - generated/agent
      - third_party$
      - builtin$
      - examples$
issues:
  uniq-by-line: true
formatters:
  enable:
    - gci
    - gofmt
  exclusions:
    generated: lax
    paths:
      - internal/inventory/tag_test.go
      - .*.pb.go
      - generated/agent
      - third_party$
      - builtin$
      - examples$
