apiVersion: v1
kind: ConfigMap
metadata:
  name: agent
  labels:
    {{- include "cluster-iq.labels" . | nindent 4 }}
    {{- include "cluster-iq.componentLabels" "agent" | nindent 4 }}
data:
  CIQ_AGENT_LISTEN_URL: 0.0.0.0:{{ .Values.agent.service.port }}
  CIQ_CREDS_FILE: /credentials/credentials
  CIQ_LOG_LEVEL: DEBUG
