---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  labels:
    {{- include "cluster-iq.labels" . | nindent 4 }}
    {{- include "cluster-iq.componentLabels" "agent" | nindent 4 }}
spec:
  replicas: {{ .Values.agent.replicaCount }}
  selector:
    matchLabels:
      {{- include "cluster-iq.selectorLabels" . | nindent 6 }}
      {{- include "cluster-iq.componentLabels" "agent" | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cluster-iq.labels" . | nindent 8 }}
        {{- with .Values.agent.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "cluster-iq.componentLabels" "agent" | nindent 8 }}
    spec:
      {{- with .Values.agent.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.agent.podSecurityContext | nindent 8 }}
      containers:
        - name: agent
          env:
          - name: CIQ_DB_URL
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: POSTGRESQL_CONNECTION_STRING
          envFrom:
          - configMapRef:
              name: agent
          securityContext:
            {{- toYaml .Values.agent.securityContext | nindent 12 }}
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          ports:
            - name: {{ .Values.agent.service.name }}
              containerPort: {{ .Values.agent.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
          startupProbe:
            tcpSocket:
              port: {{ .Values.agent.service.port }}
            {{- toYaml .Values.agent.startupProbe | nindent 12 }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.agent.service.port }}
            {{- toYaml .Values.agent.readinessProbe | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.agent.service.port }}
            {{- toYaml .Values.agent.livenessProbe | nindent 12 }}
          {{- with .Values.agent.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.agent.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
