## Build
# vim: set ft=dockerfile :
####################
FROM golang:1.19.12 AS builder

# Code copy
WORKDIR /app
COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o cluster-iq-scanner -ldflags "-X main.version=$VERSION -X main.commit=$COMMIT" ./cmd/scanner/scanner.go 

## Run
####################
FROM registry.access.redhat.com/ubi8/ubi-micro:8.8-5

# Labels
LABEL version="v0.2"
LABEL description="ClusterIQ cloud scanner"

# Binary
COPY --from=builder /app/cluster-iq-scanner /cluster-iq-scanner
# CA Certs to access AWS domains
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

# Default config
ENV CIQ_API_URL: "http://api:8080/api/v1"
ENV CIQ_CREDS_FILE: "/credentials"
ENV CIQ_LOG_LEVEL: "DEBUG"

ENTRYPOINT ["/cluster-iq-scanner"]
