apiVersion: v1
kind: ConfigMap
metadata:
  name: api
  labels:
    {{- include "cluster-iq.labels" . | nindent 4 }}
    {{- include "cluster-iq.componentLabels" "api" | nindent 4 }}
data:
  CIQ_API_LISTEN_URL: 0.0.0.0:{{ .Values.api.service.port }}
  CIQ_LOG_LEVEL: DEBUG