apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    {{- include "cluster-iq.labels" . | nindent 4 }}
    {{- include "cluster-iq.componentLabels" "api" | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.name }}
      protocol: TCP
      name: {{ .Values.api.service.name }}
  selector:
    {{- include "cluster-iq.selectorLabels" . | nindent 4 }}
    {{- include "cluster-iq.componentLabels" "api" | nindent 4 }}
