## Build
# vim: set ft=dockerfile :
####################
FROM golang:1.19.12 AS builder

# Code copy
WORKDIR /app
COPY . .

# Arguments
ARG VERSION=""
ARG COMMIT=""

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o cluster-iq-api -ldflags "-X main.version=$VERSION -X main.commit=$COMMIT" ./cmd/api/*.go

## Run
####################
FROM registry.access.redhat.com/ubi8/ubi-micro:8.8-5

# Labels
LABEL version=$VERSION
LABEL description="ClusterIQ API"

# Binary
COPY --from=builder /app/cluster-iq-api /cluster-iq-api

ENV CIQ_API_HOST="0.0.0.0"
ENV CIQ_API_PORT="8080"
ENV CIQ_DB_HOST="127.0.0.1"
ENV CIQ_DB_PORT="6379"
ENV CIQ_DB_PASS=""

EXPOSE 8080

ENTRYPOINT ["/cluster-iq-api"]
