kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cluster-iq-code
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: gp3
  volumeMode: Filesystem
