---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  labels:
    app: cluster-iq
    component: config
data:
  REACT_APP_CIQ_API_URL: "https://api-cluster-iq.apps.cn-ai-lab.6aw6.p1.openshiftapps.com/api/v1"
  CIQ_API_URL: 'http://api:8080/api/v1'
  CIQ_API_LISTEN_URL: "0.0.0.0:8080"
  CIQ_DB_URL: "postgresql://user:password@pgsql:5432/clusteriq?sslmode=disable"
  CIQ_CREDS_FILE: "/credentials/credentials"
  CIQ_LOG_LEVEL: "DEBUG"
  POSTGRESQL_USER: "user"
  POSTGRESQL_PASSWORD: "password"
  POSTGRESQL_DATABASE: "clusteriq"
  POSTGRESQL_ADMIN_PASSWORD: "admin"
  POSTGRESQL_MAX_CONNECTIONS: "100"
