---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgsql
  labels:
    app: cluster-iq
    component: db
spec:
  selector:
    matchLabels:
      app: cluster-iq
      component: db
  replicas: 1
  template:
    metadata:
      labels:
        app: cluster-iq
        component: db
    spec:
      containers:
        - name: pgsql
          image: registry.redhat.io/rhel8/postgresql-12@sha256:a6230cba71eb33e67fffc21161929de4bc618bc5e2f21fbec3c4c227205c2061
          envFrom:
            - configMapRef:
                name: config
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: cluster-iq-data
              mountPath: /var/lib/pgsql/data

  volumeClaimTemplates:
    - metadata:
        name: cluster-iq-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi



---
apiVersion: v1
kind: Service
metadata:
  name: pgsql
spec:
  type: ClusterIP
  selector:
    app: cluster-iq
    component: db
  ports:
    - name: pgsql
      protocol: TCP
      port: 5432
      targetPort: 5432


---
kind: Job
apiVersion: batch/v1
metadata:
  name: init-pgsql
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 6
  template:
    metadata:
      labels:
        app: cluster-iq
        component: db
    spec:
      volumes:
        - name: init
          configMap:
            name: pgsql-init
      containers:
        - name: init-pgsql
          image: registry.redhat.io/rhel8/postgresql-12@sha256:a6230cba71eb33e67fffc21161929de4bc618bc5e2f21fbec3c4c227205c2061
          command: ["/bin/sh", "-c"]
          args: ['while true; do psql postgresql://user:password@pgsql:5432/clusteriq -c "SELECT true" && break || sleep 2; done; psql postgresql://user:password@pgsql:5432/clusteriq < /var/lib/pgsql/init.sql']
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: config
          volumeMounts:
            - name: init
              mountPath: /var/lib/pgsql/init.sql
              subPath: init.sql
          imagePullPolicy: Always
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  completionMode: NonIndexed
  suspend: false
