---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scanner
  labels:
    app: cluster-iq
    component: api
spec:
  schedule: '00 * * * *'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scanner
              image: quay.io/ecosystem-appeng/cluster-iq-scanner:v0.2
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "50m"
                limits:
                  memory: "128Mi"
                  cpu: "200m"
              envFrom:
                - configMapRef:
                    name: config
              volumeMounts:
                - name: credentials
                  mountPath: /credentials
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: credentials
              secret:
                secretName: credentials

