apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: vault-kms-creds
  namespace: hashicorp-vault
spec:
  secretRef:
    name: vault-kms-creds
    namespace: hashicorp-vault
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - action:
      - kms:Encrypt
      - kms:Decrypt
      - kms:DescribeKey
      effect: Allow
      resource: "REPLACE_WITH_YOUR_KMS_KEY_ARN"
