package dto

import (
	"time"
)

// Cluster is the object to store Openshift Clusters and its properties
type Cluster struct {
	// ID is the unique key to identify every cluster independently of which account it belongs
	// Its built as "name+infra_id+account"
	ID string `json:"id"`

	// Cluster's Name. Must be unique per Account
	Name string `json:"name"`

	// InfraID is the infrastructure ID generated by openshift-installer during the installation.Cluster (Could be undefined)
	InfraID string `json:"infra_id"`

	// Infrastructure provider identifier.
	Provider string `json:"provider"`

	// Defines the status of the cluster if its infrastructure is running or not or it was removed
	Status string `json:"status"`

	// Region where the cluster is located
	Region string `json:"region"`

	// AccountName is the name of the account the cluster belongs to.
	AccountName string `json:"accountName"`

	// Openshift Console URL. Might not be accessible if its protected
	ConsoleLink string `json:"consoleLink"`

	// Instances count
	InstanceCount int `json:"instanceCount"`

	// Last scan timestamp
	LastScanTimestamp time.Time `json:"lastScanTimestamp"`

	// Creation timestamp
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Amount of days since the cluster was created
	Age int `json:"age"`

	// Cluster's owner
	Owner string `json:"owner"`

	// Total cost (US Dollars)
	TotalCost float64 `json:"totalCost"`

	// Cost Last 15d
	Last15DaysCost float64 `json:"last15DaysCost"`

	// Last month cost
	LastMonthCost float64 `json:"lastMonthCost"`

	// Current month so far cost
	CurrentMonthSoFarCost float64 `json:"currentMonthSoFarCost"`

	// Cluster's instance (nodes) lists
	// TODO: Should it be here? omitempty?
	Instances []Instance `json:"instances"`
}
