package dto

import (
	"time"

	"github.com/RHEcosystemAppEng/cluster-iq/internal/inventory"
)

// ClusterDTO is the object to store Openshift Clusters and its properties
type ClusterDTO struct {
	// ID is the unique key to identify every cluster independently of which account it belongs
	// Its built as "name+infra_id+account"
	ID string `json:"id"`

	// ClusterDTO's Name. Must be unique per Account
	Name string `json:"name"`

	// InfraID is the infrastructure ID generated by openshift-installer during the installation.ClusterDTO (Could be undefined)
	InfraID string `json:"infra_id"`

	// Infrastructure provider identifier.
	//TODO
	Provider inventory.CloudProvider `json:"provider"`

	// Defines the status of the cluster if its infrastructure is running or not or it was removed
	//TODO
	Status inventory.InstanceStatus `json:"status"`

	// The region of the infrastructure provider in which the cluster is deployed
	Region string `json:"region"`

	// Account name which this cluster belongs to
	AccountName string `json:"accountName"`

	// Openshift Console URL. Might not be accessible if its protected
	ConsoleLink string `json:"consoleLink"`

	// Instances count
	InstanceCount int `json:"instanceCount"`

	// Last scan timestamp of the cluster
	LastScanTimestamp time.Time `json:"lastScanTimestamp"`

	// Timestamp when the cluster was created
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Amount of days since the cluster was created
	Age int `json:"age"`

	// ClusterDTO's owner
	Owner string `json:"owner"`

	// Total cost (US Dollars)
	TotalCost float64 `json:"totalCost"`

	// Cost Last 15d
	Last15DaysCost float64 `json:"last15DaysCost"`

	// Last month cost
	LastMonthCost float64 `json:"lastMonthCost"`

	// Current month so far cost
	CurrentMonthSoFarCost float64 `json:"currentMonthSoFarCost"`

	// ClusterDTO's instance (nodes) lists
	Instances []Instance
}

// Cluster represents the data transfer object for a cluster.
type Cluster struct {
	ID                    string     `json:"id"`
	Name                  string     `json:"name"`
	InfraID               string     `json:"infra_id"`
	Provider              string     `json:"provider"`
	Status                string     `json:"status"`
	Region                string     `json:"region"`
	AccountName           string     `json:"account_name"`
	ConsoleLink           string     `json:"console_link"`
	InstanceCount         int        `json:"instance_count"`
	LastScanTimestamp     time.Time  `json:"last_scan_timestamp"`
	CreationTimestamp     time.Time  `json:"creation_timestamp"`
	Age                   int        `json:"age"`
	Owner                 string     `json:"owner"`
	TotalCost             float64    `json:"total_cost"`
	Last15DaysCost        float64    `json:"last_15_days_cost"`
	LastMonthCost         float64    `json:"last_month_cost"`
	CurrentMonthSoFarCost float64    `json:"current_month_so_far_cost"`
	Instances             []Instance `json:"instances,omitempty"`
	Tags                  []Tag      `json:"tags,omitempty"`
}
