// THIS FILE IS AUTOGENERATED. DO NOT EDIT.

package repositories

import (
	"context"
	"fmt"

	"github.com/RHEcosystemAppEng/cluster-iq/internal/audit"
	"github.com/RHEcosystemAppEng/cluster-iq/internal/models"
	"github.com/RHEcosystemAppEng/cluster-iq/internal/models/db"
	"github.com/RHEcosystemAppEng/cluster-iq/internal/db_client"
)

var _ EventRepository = (*eventRepositoryImpl)(nil)

// EventRepository defines the interface for data access operations for events.
type EventRepository interface {
	ListSystemEvents(ctx context.Context, opts models.ListOptions) ([]db.SystemEventDBResponse, int, error)
	ListClusterEvents(ctx context.Context, opts models.ListOptions) ([]db.ClusterEventDBResponse, int, error)
	AddEvent(ctx context.Context, events audit.AuditLog) (int64, error)
	AddEvents(ctx context.Context, events audit.AuditLog) (int64, error)
	UpdateEventStatus(ctx context.Context, eventID int64, result string) error
}

type eventRepositoryImpl struct {
	db *dbclient.DBClient
}

func NewEventRepository(db *dbclient.DBClient) EventRepository {
	return &eventRepositoryImpl{db: db}
}

// ListSystemEvents retrieves system-wide events with extended metadata.
func (r *eventRepositoryImpl) ListSystemEvents(ctx context.Context, opts models.ListOptions) ([]db.SystemEventDBResponse, int, error) {
	var events []db.SystemEventDBResponse

	if err := r.db.Select(events, "audit_logs", opts, "id", "*"); err != nil {
		return events, 0, fmt.Errorf("failed to list clusters: %w", err)
	}

	return events, len(events), nil
}

// ListClusterEvents retrieves events for a specific resource (like a cluster).
func (r *eventRepositoryImpl) ListClusterEvents(ctx context.Context, opts models.ListOptions) ([]db.ClusterEventDBResponse, int, error) {
	var events []db.ClusterEventDBResponse

	if err := r.db.Select(events, "audit_logs", opts, "id", "*"); err != nil {
		return events, 0, fmt.Errorf("failed to list clusters: %w", err)
	}

	return events, len(events), nil
}
func (r *eventRepositoryImpl) AddEvent(ctx context.Context, event audit.AuditLog) (int64, error) {
	if err := r.db.Insert(InsertClustersQuery, event); err != nil {
		// TODO FIX event ID return
		return 0,err
	}
	return 0,nil
}

// AddEvent inserts a new audit event into the database and returns the event ID.
func (r *eventRepositoryImpl) AddEvents(ctx context.Context, events audit.AuditLog) (int64, error) {
	if err := r.db.Insert(InsertClustersQuery, events); err != nil {
		// TODO FIX event ID return
		return 0,err
	}
	return 0,nil
}

// UpdateEventStatus updates the result status of an audit event.
func (r *eventRepositoryImpl) UpdateEventStatus(ctx context.Context, eventID int64, result string) error {
	//TODO
	return nil
}
