{{- $existing := (lookup "v1" "Secret" .Release.Namespace "postgresql") -}}
{{- if $existing -}}
{{ $existing | toYaml }}
{{- else -}}
{{- $user := "user" -}}
{{- $userPassword := randAlphaNum 32 -}}
{{- $adminPassword := randAlphaNum 32 -}}
{{- $database := "clusteriq" -}}
{{- $dbHost := printf "pgsql.%s.svc.cluster.local" .Release.Namespace -}}
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  labels:
    {{- include "cluster-iq.labels" . | nindent 4 }}
    {{- include "cluster-iq.componentLabels" "database" | nindent 4 }}
type: Opaque
data:
  POSTGRESQL_ADMIN_PASSWORD: {{ $adminPassword | b64enc | quote }}
  POSTGRESQL_USER: {{ $user | b64enc | quote }}
  POSTGRESQL_PASSWORD: {{ $userPassword | b64enc | quote }}
  POSTGRESQL_DATABASE: {{ $database | b64enc | quote }}
  POSTGRESQL_CONNECTION_STRING: {{ printf "postgresql://%s:%s@%s:5432/%s?sslmode=disable" $user $userPassword $dbHost $database | b64enc | quote }}
{{- end -}}