apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-template
  labels:
    {{- include "cluster-iq.labels" . | nindent 4 }}
    {{- include "cluster-iq.componentLabels" "console" | nindent 4 }}
immutable: true
data:
  nginx.conf.template: |-
    worker_processes auto;
    worker_rlimit_nofile 65535;

    include /etc/nginx/modules-enabled/*.conf;

    events {
        multi_accept on;
        worker_connections 65535;
    }

    http {
        charset utf-8;
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        types_hash_max_size 2048;
        types_hash_bucket_size 64;
        client_max_body_size 16M;

        # MIME
        include mime.types;
        default_type application/octet-stream;

        # Logging
        access_log /dev/stdout;
        error_log /dev/stdout info;

        server {
            listen 8080 default_server;
            server_name _;
            root /opt/app-root/src;
            index index.html;

            # security headers
            add_header X-XSS-Protection "1; mode=block" always;
            add_header X-Content-Type-Options "nosniff" always;
            add_header Referrer-Policy "no-referrer-when-downgrade" always;
            add_header Content-Security-Policy "default-src 'self' http: https: data: blob: 'unsafe-inline'; frame-ancestors 'self';" always;
            add_header Permissions-Policy "interest-cohort=()" always;

            # . files
            location ~ /\.(?!well-known) {
                deny all;
            }

            # proxy API requests to backend
            location /api/ {
                proxy_pass ${BACKEND_URL}/api/v1/;
                proxy_http_version 1.1;

                # Proxy headers
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

                # Proxy timeouts
                proxy_connect_timeout 60s;
                proxy_send_timeout 60s;
                proxy_read_timeout 60s;
            }

            # index.html fallback
            location / {
                try_files $uri $uri/ /index.html;
            }

            # Serve static assets
            location /assets/ {
                expires 7d;
                add_header Cache-Control "public";
            }

            # assets, media
            location ~* \.(?:css(\.map)?|js(\.map)?|jpe?g|png|gif|ico|cur|heic|webp|tiff?)$ {
                expires 7d;
            }

            # svg, fonts
            location ~* \.(?:svgz?|ttf|ttc|otf|eot|woff2?)$ {
                add_header Access-Control-Allow-Origin "*";
                expires 7d;
            }

            # gzip
            gzip on;
            gzip_vary on;
            gzip_proxied any;
            gzip_comp_level 6;
            gzip_types text/plain text/css text/xml application/json application/javascript application/rss+xml application/atom+xml image/svg+xml;
        }
    }
