apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: console
  labels:
    {{- include "cluster-iq.labels" . | nindent 4 }}
    {{- include "cluster-iq.componentLabels" "console" | nindent 4 }}
spec:
  to:
    kind: Service
    name: console
    weight: 100
  port:
    targetPort: oauth-proxy
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect