apiVersion: v1
kind: Service
metadata:
  name: console
  labels:
    {{- include "cluster-iq.labels" . | nindent 4 }}
    {{- include "cluster-iq.componentLabels" "console" | nindent 4 }}
  {{- with .Values.console.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.console.service.type }}
  ports:
    - name: {{ .Values.console.service.name }}
      port: {{ .Values.console.service.port }}
      targetPort: {{ .Values.console.service.name }}
      protocol: TCP
    - name: oauth-proxy
      port: 8443
      targetPort: oauth-proxy
      protocol: TCP
  selector:
    {{- include "cluster-iq.selectorLabels" . | nindent 4 }}
    {{- include "cluster-iq.componentLabels" "console" | nindent 4 }}
