kind: CronJob
apiVersion: batch/v1
metadata:
  name: scanner
  labels:
    {{- include "cluster-iq.labels" . | nindent 4 }}
    {{- include "cluster-iq.componentLabels" "api" | nindent 4 }}
spec:
  schedule: 0 0 * * *
  concurrencyPolicy: Allow
  suspend: false
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: credentials
              secret:
                secretName: credentials
          containers:
            - name: scanner
              image: "{{ .Values.scanner.image.repository }}:{{ .Values.scanner.image.tag | default .Chart.AppVersion }}"
              envFrom:
                - configMapRef:
                    name: scanner
              volumeMounts:
                - name: credentials
                  readOnly: true
                  mountPath: /credentials
              imagePullPolicy: IfNotPresent
              resources:
                {{- toYaml .Values.scanner.resources | nindent 16 }}
          restartPolicy: OnFailure
