{{- if .Values.vault.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cluster-iq-credentials-scanner
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-iq.labels" . | nindent 4 }}
spec:
  provider: vault
  parameters:
    vaultAddress: "{{ .Values.vault.address }}"
    roleName: "scanner"
    objects: |
      - objectName: "credentials"
        secretPath: "{{ .Values.vault.secretPath }}"
        secretKey: "{{ .Values.vault.secretKey }}"
{{- end -}}
