// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package convert

import (
	actions "github.com/RHEcosystemAppEng/cluster-iq/internal/actions"
	inventory "github.com/RHEcosystemAppEng/cluster-iq/internal/inventory"
	db "github.com/RHEcosystemAppEng/cluster-iq/internal/models/db"
	dto "github.com/RHEcosystemAppEng/cluster-iq/internal/models/dto"
)

type ConverterImpl struct{}

func (c *ConverterImpl) ToAccountDTO(source db.AccountDBResponse) dto.AccountDTOResponse {
	var dtoAccountDTOResponse dto.AccountDTOResponse
	dtoAccountDTOResponse.AccountID = source.AccountID
	dtoAccountDTOResponse.AccountName = source.AccountName
	dtoAccountDTOResponse.Provider = inventory.Provider(source.Provider)
	dtoAccountDTOResponse.LastScanTimestamp = Time(source.LastScanTimestamp)
	dtoAccountDTOResponse.CreatedAt = Time(source.CreatedAt)
	dtoAccountDTOResponse.ClusterCount = source.ClusterCount
	dtoAccountDTOResponse.TotalCost = source.TotalCost
	dtoAccountDTOResponse.Last15DaysCost = source.Last15DaysCost
	dtoAccountDTOResponse.LastMonthCost = source.LastMonthCost
	dtoAccountDTOResponse.CurrentMonthSoFarCost = source.CurrentMonthSoFarCost
	return dtoAccountDTOResponse
}
func (c *ConverterImpl) ToAccountDTOs(source []db.AccountDBResponse) []dto.AccountDTOResponse {
	var dtoAccountDTOResponseList []dto.AccountDTOResponse
	if source != nil {
		dtoAccountDTOResponseList = make([]dto.AccountDTOResponse, len(source))
		for i := 0; i < len(source); i++ {
			dtoAccountDTOResponseList[i] = c.ToAccountDTO(source[i])
		}
	}
	return dtoAccountDTOResponseList
}
func (c *ConverterImpl) ToActionDTO(source db.ActionDBResponse) dto.ActionDTOResponse {
	var dtoActionDTOResponse dto.ActionDTOResponse
	dtoActionDTOResponse.ID = source.ID
	dtoActionDTOResponse.Type = source.Type
	dtoActionDTOResponse.Time = NullTime(source.Time)
	dtoActionDTOResponse.CronExp = NullString(source.CronExp)
	dtoActionDTOResponse.Operation = source.Operation
	dtoActionDTOResponse.Status = source.Status
	dtoActionDTOResponse.Enabled = source.Enabled
	dtoActionDTOResponse.ClusterID = source.ClusterID
	dtoActionDTOResponse.Region = source.Region
	dtoActionDTOResponse.AccountID = source.AccountID
	dtoActionDTOResponse.Instances = StringArray(source.Instances)
	return dtoActionDTOResponse
}
func (c *ConverterImpl) ToActionDTOs(source []db.ActionDBResponse) []dto.ActionDTOResponse {
	var dtoActionDTOResponseList []dto.ActionDTOResponse
	if source != nil {
		dtoActionDTOResponseList = make([]dto.ActionDTOResponse, len(source))
		for i := 0; i < len(source); i++ {
			dtoActionDTOResponseList[i] = c.ToActionDTO(source[i])
		}
	}
	return dtoActionDTOResponseList
}
func (c *ConverterImpl) ToClusterDTO(source db.ClusterDBResponse) dto.ClusterDTOResponse {
	var dtoClusterDTOResponse dto.ClusterDTOResponse
	dtoClusterDTOResponse.ClusterID = source.ClusterID
	dtoClusterDTOResponse.ClusterName = source.ClusterName
	dtoClusterDTOResponse.InfraID = source.InfraID
	dtoClusterDTOResponse.Provider = inventory.Provider(source.Provider)
	dtoClusterDTOResponse.Status = inventory.ResourceStatus(source.Status)
	dtoClusterDTOResponse.Region = source.Region
	dtoClusterDTOResponse.AccountID = source.AccountID
	dtoClusterDTOResponse.AccountName = source.AccountName
	dtoClusterDTOResponse.ConsoleLink = source.ConsoleLink
	dtoClusterDTOResponse.InstanceCount = source.InstanceCount
	dtoClusterDTOResponse.LastScanTimestamp = Time(source.LastScanTimestamp)
	dtoClusterDTOResponse.CreatedAt = Time(source.CreatedAt)
	dtoClusterDTOResponse.Age = source.Age
	dtoClusterDTOResponse.Owner = source.Owner
	dtoClusterDTOResponse.TotalCost = source.TotalCost
	dtoClusterDTOResponse.Last15DaysCost = source.Last15DaysCost
	dtoClusterDTOResponse.LastMonthCost = source.LastMonthCost
	dtoClusterDTOResponse.CurrentMonthSoFarCost = source.CurrentMonthSoFarCost
	return dtoClusterDTOResponse
}
func (c *ConverterImpl) ToClusterDTOs(source []db.ClusterDBResponse) []dto.ClusterDTOResponse {
	var dtoClusterDTOResponseList []dto.ClusterDTOResponse
	if source != nil {
		dtoClusterDTOResponseList = make([]dto.ClusterDTOResponse, len(source))
		for i := 0; i < len(source); i++ {
			dtoClusterDTOResponseList[i] = c.ToClusterDTO(source[i])
		}
	}
	return dtoClusterDTOResponseList
}
func (c *ConverterImpl) ToClusterEventDTO(source db.ClusterEventDBResponse) dto.ClusterEventDTOResponse {
	var dtoClusterEventDTOResponse dto.ClusterEventDTOResponse
	dtoClusterEventDTOResponse.ID = source.ID
	dtoClusterEventDTOResponse.Action = source.Action
	dtoClusterEventDTOResponse.ResourceID = source.ResourceID
	dtoClusterEventDTOResponse.ResourceType = source.ResourceType
	dtoClusterEventDTOResponse.EventTimestamp = Time(source.EventTimestamp)
	dtoClusterEventDTOResponse.Result = actions.ActionStatus(source.Result)
	dtoClusterEventDTOResponse.Severity = source.Severity
	dtoClusterEventDTOResponse.TriggeredBy = source.TriggeredBy
	if source.Description != nil {
		xstring := *source.Description
		dtoClusterEventDTOResponse.Description = &xstring
	}
	return dtoClusterEventDTOResponse
}
func (c *ConverterImpl) ToClusterEventDTOs(source []db.ClusterEventDBResponse) []dto.ClusterEventDTOResponse {
	var dtoClusterEventDTOResponseList []dto.ClusterEventDTOResponse
	if source != nil {
		dtoClusterEventDTOResponseList = make([]dto.ClusterEventDTOResponse, len(source))
		for i := 0; i < len(source); i++ {
			dtoClusterEventDTOResponseList[i] = c.ToClusterEventDTO(source[i])
		}
	}
	return dtoClusterEventDTOResponseList
}
func (c *ConverterImpl) ToExpenseDTO(source db.ExpenseDBResponse) dto.ExpenseDTOResponse {
	var dtoExpenseDTOResponse dto.ExpenseDTOResponse
	dtoExpenseDTOResponse.InstanceID = source.InstanceID
	dtoExpenseDTOResponse.Amount = source.Amount
	dtoExpenseDTOResponse.Date = Time(source.Date)
	return dtoExpenseDTOResponse
}
func (c *ConverterImpl) ToExpenseDTOs(source []db.ExpenseDBResponse) []dto.ExpenseDTOResponse {
	var dtoExpenseDTOResponseList []dto.ExpenseDTOResponse
	if source != nil {
		dtoExpenseDTOResponseList = make([]dto.ExpenseDTOResponse, len(source))
		for i := 0; i < len(source); i++ {
			dtoExpenseDTOResponseList[i] = c.ToExpenseDTO(source[i])
		}
	}
	return dtoExpenseDTOResponseList
}
func (c *ConverterImpl) ToInstanceDTO(source db.InstanceDBResponse) dto.InstanceDTOResponse {
	var dtoInstanceDTOResponse dto.InstanceDTOResponse
	dtoInstanceDTOResponse.InstanceID = source.InstanceID
	dtoInstanceDTOResponse.InstanceName = source.InstanceName
	dtoInstanceDTOResponse.InstanceType = source.InstanceType
	dtoInstanceDTOResponse.Provider = inventory.Provider(source.Provider)
	dtoInstanceDTOResponse.AvailabilityZone = source.AvailabilityZone
	dtoInstanceDTOResponse.Status = inventory.ResourceStatus(source.Status)
	dtoInstanceDTOResponse.ClusterID = source.ClusterID
	dtoInstanceDTOResponse.ClusterName = source.ClusterName
	dtoInstanceDTOResponse.LastScanTimestamp = Time(source.LastScanTimestamp)
	dtoInstanceDTOResponse.CreatedAt = Time(source.CreatedAt)
	dtoInstanceDTOResponse.Age = source.Age
	dtoInstanceDTOResponse.TotalCost = source.TotalCost
	dtoInstanceDTOResponse.Last15DaysCost = source.Last15DaysCost
	dtoInstanceDTOResponse.LastMonthCost = source.LastMonthCost
	dtoInstanceDTOResponse.CurrentMonthSoFarCost = source.CurrentMonthSoFarCost
	dtoInstanceDTOResponse.Tags = TagDBResponsesToDTO(source.Tags)
	return dtoInstanceDTOResponse
}
func (c *ConverterImpl) ToInstanceDTOs(source []db.InstanceDBResponse) []dto.InstanceDTOResponse {
	var dtoInstanceDTOResponseList []dto.InstanceDTOResponse
	if source != nil {
		dtoInstanceDTOResponseList = make([]dto.InstanceDTOResponse, len(source))
		for i := 0; i < len(source); i++ {
			dtoInstanceDTOResponseList[i] = c.ToInstanceDTO(source[i])
		}
	}
	return dtoInstanceDTOResponseList
}
func (c *ConverterImpl) ToSystemEventDTO(source db.SystemEventDBResponse) dto.SystemEventDTOResponse {
	var dtoSystemEventDTOResponse dto.SystemEventDTOResponse
	dtoSystemEventDTOResponse.ClusterEventDTOResponse = c.ToClusterEventDTO(source.ClusterEventDBResponse)
	dtoSystemEventDTOResponse.AccountID = source.AccountID
	dtoSystemEventDTOResponse.Provider = source.Provider
	return dtoSystemEventDTOResponse
}
func (c *ConverterImpl) ToSystemEventDTOs(source []db.SystemEventDBResponse) []dto.SystemEventDTOResponse {
	var dtoSystemEventDTOResponseList []dto.SystemEventDTOResponse
	if source != nil {
		dtoSystemEventDTOResponseList = make([]dto.SystemEventDTOResponse, len(source))
		for i := 0; i < len(source); i++ {
			dtoSystemEventDTOResponseList[i] = c.ToSystemEventDTO(source[i])
		}
	}
	return dtoSystemEventDTOResponseList
}
func (c *ConverterImpl) ToTagDTO(source db.TagDBResponse) dto.TagDTOResponse {
	var dtoTagDTOResponse dto.TagDTOResponse
	dtoTagDTOResponse.Key = source.Key
	dtoTagDTOResponse.Value = source.Value
	dtoTagDTOResponse.InstanceID = source.InstanceID
	return dtoTagDTOResponse
}
func (c *ConverterImpl) ToTagDTOs(source []db.TagDBResponse) []dto.TagDTOResponse {
	var dtoTagDTOResponseList []dto.TagDTOResponse
	if source != nil {
		dtoTagDTOResponseList = make([]dto.TagDTOResponse, len(source))
		for i := 0; i < len(source); i++ {
			dtoTagDTOResponseList[i] = c.ToTagDTO(source[i])
		}
	}
	return dtoTagDTOResponseList
}
