name: Cluster IQ Container image building

on:
  push:
    branches:
      - main
      - release-.*
      - release-.*-rc-.*
      - feature/gh-actions-122
  pull_request:
    branches:
      - main
      - release-.*
      - release-.*-rc-.*

jobs:
  build-and-push:
    runs-on:
      - self-hosted
      - rhel-ubi

    permissions:
      content: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Podman and Buildah
        run: |
          sudo dnf install -y podman buildah skopeo

      - name: Login to Quay.io with Podman
        run: |
          echo "${{ secrets.QUAY_PASSWORD }}" | podman login quay.io -u "${{ secrets.QUAY_USERNAME }}" --password-stdin


      - name: Determine Image Tags
        id: vars
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            TAG="latest"
          else
            TAG=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///' | tr '/' '-')
          fi
          echo "IMAGE_TAG=${TAG}" >> $GITHUB_ENV

      - name: Build and Push Images
        run: |
          IMAGES="api agent scanner"
          for IMAGE in $IMAGES; do
            echo "Building and pushing quay.io/${{ secrets.QUAY_ORG_NAME }}/cluster-iq-${IMAGE}:${IMAGE_TAG}"
            podman build \
              --platform linux/amd64 \
              -t quay.io/${{ secrets.QUAY_ORG_NAME }}/cluster-iq-${IMAGE}:${IMAGE_TAG} \
              -f ./deployments/containerfiles/Containerfile-${IMAGE} .

            podman push quay.io/${{ secrets.QUAY_ORG_NAME }}/cluster-iq-${IMAGE}:${IMAGE_TAG}

          done

          podman logout
