name: Cluster IQ Container image building

on:
  push:
    branches:
      - main
      - release-.*
      - release-.*-rc-.*
      - feature/gh-actions-122
  pull_request:
    branches:
      - main
      - release-.*
      - release-.*-rc-.*

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Podman and Buildah
        run: |
          sudo apt update
          sudo apt -y install podman

      - name: Install Golang
        run: |
          sudo add-apt-repository ppa:longsleep/golang-backports
          sudo apt update
          sudo apt install golang-go

      - name: Go tidy modules
        run: |
          go mod tidy

      - name: Login to Quay.io with Podman
        run: |
          echo "${{ secrets.QUAY_PASSWORD }}" | podman login quay.io -u "${{ secrets.QUAY_USERNAME }}" --password-stdin


      - name: Determine Image Tags
        id: vars
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            TAG="latest"
          else
            TAG=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///' | tr '/' '-')
          fi
          echo "IMAGE_TAG=${TAG}" >> $GITHUB_ENV

      - name: Get Container Image build arguments
        run: |
          echo "COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "VERSION=$(cat ./VERSION)" >> $GITHUB_ENV

      - name: Build and Push Images
        run: |
          IMAGES="api agent scanner"
          for IMAGE in $IMAGES; do
            echo "Building and pushing quay.io/${{ secrets.QUAY_ORG_NAME }}/cluster-iq-${IMAGE}:${IMAGE_TAG}"
            podman build \
              --platform linux/amd64 \
              --build-arg VERSION=${VERSION} \
              --build-arg COMMIT=${COMMIT} \
              -t quay.io/${{ secrets.QUAY_ORG_NAME }}/cluster-iq-${IMAGE}:${IMAGE_TAG} \
              -f ./deployments/containerfiles/Containerfile-${IMAGE} .

            podman push quay.io/${{ secrets.QUAY_ORG_NAME }}/cluster-iq-${IMAGE}:${IMAGE_TAG}

          done

      - name: Logout
        run: |
          podman logout
