name: Cluster IQ Container image building

on:
  push:
    branches:
      - main
      - release-.*
      - release-.*-rc-.*
      - feature/gh-actions-122
  pull_request:
    branches:
      - main
      - release-.*
      - release-.*-rc-.*

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      IMAGE_TAG: ${{ steps.vars.outputs.IMAGE_TAG }}
      COMMIT: ${{ steps.vars.outputs.COMMIT }}
      VERSION: ${{ steps.vars.outputs.VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -y install podman

      - name: Determine Image Tags
        id: vars
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            TAG="latest"
          else
            TAG=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///' | tr '/' '-')
          fi
          echo "IMAGE_TAG=${TAG}" >> $GITHUB_ENV
          echo "COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "VERSION=$(cat ./VERSION)" >> $GITHUB_ENV


  api:
    runs-on: ubuntu-latest
    needs: setup
    permissions:
      contents: read
      packages: write

    steps:
      - name: Container image building
        run: |
          echo "Building API (${{ env.IMAGE_TAG }})"
          podman build \
            --platform linux/amd64 \
            --build-arg VERSION=${{ env.VERSION }} \
            --build-arg COMMIT=${{ env.COMMIT }} \
            -t quay.io/${{ secrets.QUAY_ORG_NAME }}/cluster-iq-api:${{ env.IMAGE_TAG }} \
            -f ./deployments/containerfiles/Containerfile-api .

      - name: Login to Quay.io
        run: |
          echo "${{ secrets.QUAY_PASSWORD }}" | podman login quay.io -u "${{ secrets.QUAY_USERNAME }}" --password-stdin

      - name: Container image pushing
        run: |
          podman push quay.io/${{ secrets.QUAY_ORG_NAME }}/cluster-iq-api:${{ env.IMAGE_TAG }}

      - name: Logout from Quay.io
        if: always()
        run: |
          podman logout

  agent:
    runs-on: ubuntu-latest
    needs: setup
    permissions:
      contents: read
      packages: write

    steps:
      - name: Container image building
        run: |
          echo "Building Agent (${{ env.IMAGE_TAG }})"
          podman build \
            --platform linux/amd64 \
            --build-arg VERSION=${{ env.VERSION }} \
            --build-arg COMMIT=${{ env.COMMIT }} \
            -t quay.io/${{ secrets.QUAY_ORG_NAME }}/cluster-iq-agent:${{ env.IMAGE_TAG }} \
            -f ./deployments/containerfiles/Containerfile-agent .

      - name: Login to Quay.io
        run: |
          echo "${{ secrets.QUAY_PASSWORD }}" | podman login quay.io -u "${{ secrets.QUAY_USERNAME }}" --password-stdin

      - name: Container image pushing
        run: |
          podman push quay.io/${{ secrets.QUAY_ORG_NAME }}/cluster-iq-agent:${{ env.IMAGE_TAG }}

      - name: Logout from Quay.io
        if: always()
        run: |
          podman logout

  scanner:
    runs-on: ubuntu-latest
    needs: setup
    permissions:
      contents: read
      packages: write

    steps:
      - name: Container image building
        run: |
          echo "Building Scanner (${{ env.IMAGE_TAG }})"
          podman build \
            --platform linux/amd64 \
            --build-arg VERSION=${{ env.VERSION }} \
            --build-arg COMMIT=${{ env.COMMIT }} \
            -t quay.io/${{ secrets.QUAY_ORG_NAME }}/cluster-iq-scanner:${{ env.IMAGE_TAG }} \
            -f ./deployments/containerfiles/Containerfile-scanner .

      - name: Login to Quay.io
        run: |
          echo "${{ secrets.QUAY_PASSWORD }}" | podman login quay.io -u "${{ secrets.QUAY_USERNAME }}" --password-stdin

      - name: Container image pushing
        run: |
          podman push quay.io/${{ secrets.QUAY_ORG_NAME }}/cluster-iq-scanner:${{ env.IMAGE_TAG }}

      - name: Logout from Quay.io
        if: always()
        run: |
          podman logout
