version: "3.8"

networks:
  cluster_iq:
    driver: bridge

services:
  api:
    image: quay.io/ecosystem-appeng/cluster-iq-api:latest
    container_name: api
    restart: always
    depends_on:
      init-pgsql:
        condition: service_completed_successfully
    ports:
      - 8081:8080
    environment:
      CIQ_API_LISTEN_URL: "0.0.0.0:8080"
      CIQ_AGENT_URL: "agent:50051"
      CIQ_DB_URL: "postgresql://user:password@pgsql:5432/clusteriq?sslmode=disable"
      CIQ_LOG_LEVEL: "DEBUG"
    networks:
      - cluster_iq

  scanner:
    image: quay.io/ecosystem-appeng/cluster-iq-scanner:latest
    container_name: scanner
    restart: "no"
    depends_on:
      api:
        condition: service_started
    environment:
      CIQ_API_URL: "http://api:8080/api/v1"
      CIQ_CREDS_FILE: "/credentials"
      CIQ_SKIP_NO_OPENSHIFT_INSTANCES: true
      CIQ_LOG_LEVEL: "DEBUG"
    volumes:
      - ../../secrets/credentials:/credentials:ro,Z
    networks:
      - cluster_iq

  agent:
    image: quay.io/ecosystem-appeng/cluster-iq-agent:latest
    container_name: agent
    environment:
      CIQ_API_URL: "http://api:8080/api/v1"
      CIQ_DB_URL: "postgresql://user:password@pgsql:5432/clusteriq?sslmode=disable"
      CIQ_AGENT_INSTANT_SERVICE_LISTEN_URL: "0.0.0.0:50051"
      CIQ_CREDS_FILE: "/credentials"
      CIQ_LOG_LEVEL: "DEBUG"
      CIQ_AGENT_POLLING_SECONDS_INTERVAL: 5 # Seconds
    ports:
      - 50051:50051
    volumes:
      - ../../secrets/credentials:/credentials:ro,Z
    networks:
      - cluster_iq

  pgsql:
    image: registry.redhat.io/rhel8/postgresql-12@sha256:a6230cba71eb33e67fffc21161929de4bc618bc5e2f21fbec3c4c227205c2061
    container_name: pgsql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USER: "user"
      POSTGRESQL_PASSWORD: "password"
      POSTGRESQL_DATABASE: "clusteriq"
      POSTGRESQL_ADMIN_PASSWORD: "admin"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - cluster_iq

  init-pgsql:
    image: registry.redhat.io/rhel8/postgresql-12@sha256:a6230cba71eb33e67fffc21161929de4bc618bc5e2f21fbec3c4c227205c2061
    container_name: init-pgsql
    restart: "no"
    command: |
      sh -c 'while true; do
                 psql postgresql://user:password@pgsql:5432/clusteriq -c "SELECT true" && break || sleep 2;
             done
             psql postgresql://user:password@pgsql:5432/clusteriq < /init.sql && { echo "Ok"; } || { echo "Initialization Failed"; exit 1; }
      '
    volumes:
      - ./../../db/sql/init.sql:/init.sql:ro,Z
    depends_on:
      pgsql:
        condition: service_healthy
    networks:
      - cluster_iq
