networks:
  cluster_iq:
    driver: bridge

services:
  api:
    image: quay.io/ecosystem-appeng/cluster-iq-api:latest
    container_name: api
    restart: always
    ports:
      - 8081:8080
    environment:
      CIQ_API_LISTEN_URL: "0.0.0.0:8080"
      CIQ_AGENT_URL: "agent:50051"
      CIQ_DB_URL: "postgresql://user:password@pgsql:5432/clusteriq?sslmode=disable"
      CIQ_LOG_LEVEL: "DEBUG"
    networks:
      - cluster_iq

  pgsql:
    image: quay.io/fedora/postgresql-16:16
    container_name: pgsql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USER: "user"
      POSTGRESQL_PASSWORD: "password"
      POSTGRESQL_DATABASE: "clusteriq"
      POSTGRESQL_ADMIN_PASSWORD: "admin"
    networks:
      - cluster_iq

  init-pgsql:
    image: quay.io/fedora/postgresql-16:16
    container_name: init-pgsql
    restart: "no"
    command: |
      sh -c 'while true; do
                 psql postgresql://user:password@pgsql:5432/clusteriq -c "SELECT true" && break || sleep 2;
             done
             psql postgresql://user:password@pgsql:5432/clusteriq < /init.sql && { echo "Ok"; } || { echo "Initialization Failed"; exit 1; }
      '
    volumes:
      - ./../../db/sql/init.sql:/init.sql:ro,Z
    networks:
      - cluster_iq

